### ISSUE TITLE
add webcam corner for screencast

### ISSUE THREAD

**Issue by aleksfadini** [vitorgalvao/start-recording-workflow#1]
### Feature details

This shortcut is great, but adding a webcam function would really help. I believe it should be doable via automator/quicktime. Have not look into that yet, but I'm guessing is easy enough. I hope you can consider this. Thank you!

**Comment by vitorgalvao** [comment]
There is already a way to record the webcam, it’s `webcam rec` by default. It is covered in the instructions. When you do that you get the webcam window preview. Do that followed by a screen recording.
